#VIDEO
#https://mpv.io/manual/master/#profiles
profile=high-quality
#https://mpv.io/manual/master/#video-output-drivers
vo=gpu-next
#Dither (must be set to match your monitor's bit depth)
dither-depth=8
#Hardware video acceleration
hwdec=auto-safe

#AUDIO
#https://mpv.io/manual/master/#audio-output-drivers | Use 'mpv --ao=help' to see your drivers
ao=wasapi,sdl,openal,pcm,null
volume=65
volume-max=200

#OSD settings->https://mpv.io/manual/master/#osd
osd-on-seek=msg-bar
osd-fractions
osd-level=1
osd-font='Yu Gothic'
osd-italic=no
osd-bold=yes
osd-font-size=60

#WINDOWS('force-window' is a must-have for Windows)
taskbar-progress=yes
autofit-smaller=75%x75%
autofit-larger=75%x75%
force-window=yes
border=no
#Stop resizing when jumping to the next file with a different resolution
auto-window-resize=no

#PLAYBACK
#auto-loop (single file loop takes precedence over looping a playlist)
loop-file=inf
loop-playlist=inf
#Generate a playlist from same files in the same directory
autocreate-playlist=same
#mpv doesn't auto-close when it runs out of files to play and just typing 'mpv' in cmd can open it
idle=yes
#Saves not just playing position but also volume settings for the file
save-position-on-quit
#Force seeking (if seeking doesn't work)
force-seekable=yes
#https://mpv.io/manual/master/#files-on-windows (keybinds still keyframe seek)
hr-seek=absolute
#Cursor hide in ms
cursor-autohide=100

#Subtitle configurations
sub-auto=fuzzy
#Helps mpv grab external subs even if the file names are not an exact match

#Audio configurations
alang=jpn
#Prioritise playing Japanese audio (over English audio for example)

#Screenshot configurations->https://mpv.io/manual/master/#options-screenshot-format
screenshot-format=webp
screenshot-template="%F - [%P] (%#01n)"
screenshot-jpeg-quality=100
screenshot-jpeg-source-chroma=yes
screenshot-png-compression=9
screenshot-png-filter=5
screenshot-webp-lossless=yes
#screenshot-webp-quality=<0-100> | The default is 75. | Higher means better quality (if lossy) or better compression (if lossless). | Not setting it to 100 as screenshooting would take too long and compression at 75 is reasonably good.
screenshot-webp-compression=6
screenshot-jxl-distance=0.1
#Lower distance means better quality. Lossless is 0.0, use 0.1 for "visually lossless" screenshots.
screenshot-jxl-effort=9
#Higher effort (usually) means better compression, but takes more CPU time. The default is 4.

#Conditional profiles must be below main profiles so they don't mess up your code
[m3u8]
profile-cond = (filename:match"%.m3u8$") ~= nil
loop-file=no
autocreate-playlist=no
save-position-on-quit=no

[Music]
profile-cond = (filename:match"%.mp3$" or filename:match"%.m4a$" or filename:match"%.flac$" or filename:match"%.opus$" or filename:match"%.wav$" or filename:match"%.ogg$" or filename:match"%.mka$") ~= nil
save-position-on-quit=no

[Odd Dimensions]
profile-cond=(width % 2 == 1 or height % 2 == 1) 
hwdec=auto-copy
profile-restore=copy
#'--hwdec=auto-safe' does not work with odd-dimension videos

#Potential configs I'm not using atm from https://thewiki.moe/tutorials/mpv/
#scale-antiring=0.6
#Always open the video player in full screen
#fullscreen=yes
#Don't close the player after finishing the video
#keep-open=yes